name: Backend CI (tests + SonarCloud)

on:
  push: { branches: ["**"] }
  pull_request: { branches: ["**"] }

defaults:
  run:
    working-directory: .

jobs:
  test-and-sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Tests + Coverage (JaCoCo)
        run: mvn -B -ntp clean verify

      - name: SonarCloud Scan
        if: ${{ vars.USE_SONARCLOUD == 'true' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}
          SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
        run: |
          mvn -B -ntp org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.token="$SONAR_TOKEN" \
            -Dsonar.organization="$SONAR_ORGANIZATION" \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
